export const usersTypes = {
  LOADED: 'USER_LOADED',
  LOADEDPLUS: 'USER_LOADEDPLUS',
  FOLLOWERS_LOADED: 'USER_FOLLOWERS_LOADED',
  FOLLOWERS_LOADEDPLUS: 'USER_FOLLOWERS_LOADEDPLUS',
  LOGOUT: 'USER_LOGOUT',
};